//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_adinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string imgUrl { get; set; }
        public string webUrl { get; set; }
        public bool isTop { get; set; }
    }
}
