//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_KindInfo
    {
        public db_KindInfo()
        {
            this.db_sonkindInfo = new HashSet<db_sonkindInfo>();
        }
    
        public int Id { get; set; }
        public string KindName { get; set; }
        public string pagecontent { get; set; }
    
        public virtual ICollection<db_sonkindInfo> db_sonkindInfo { get; set; }
    }
}
