//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ProductInfo
    {
        public db_ProductInfo()
        {
            this.db_ProductImgInfo = new HashSet<db_ProductImgInfo>();
        }
    
        public int Id { get; set; }
        public string PName { get; set; }
        public double CostPrice { get; set; }
        public double SalePrice { get; set; }
        public string PContent { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime CanSaleTime { get; set; }
        public bool isFreePost { get; set; }
        public string BrandName { get; set; }
        public int KindId { get; set; }
        public bool isSale { get; set; }
        public string taobaoUrl { get; set; }
        public bool IsUseTaobao { get; set; }
        public bool isTop { get; set; }
        public int TopOrder { get; set; }
        public bool IsHot { get; set; }
        public int HotOrder { get; set; }
        public string ImgUrl { get; set; }
    
        public virtual ICollection<db_ProductImgInfo> db_ProductImgInfo { get; set; }
        public virtual db_sonkindInfo db_sonkindInfo { get; set; }
    }
}
