//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_sonkindInfo
    {
        public db_sonkindInfo()
        {
            this.db_ProductInfo = new HashSet<db_ProductInfo>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int kindid { get; set; }
        public string pagecontent { get; set; }
        public string kindName { get; set; }
    
        public virtual db_KindInfo db_KindInfo { get; set; }
        public virtual ICollection<db_ProductInfo> db_ProductInfo { get; set; }
    }
}
