//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_UserInfo
    {
        public db_UserInfo()
        {
            this.db_UserAddressInfo = new HashSet<db_UserAddressInfo>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string UserSex { get; set; }
        public string UserBrithday { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime UserCreateTime { get; set; }
        public System.DateTime UserLastLoginTime { get; set; }
        public string User { get; set; }
        public string fristQ { get; set; }
        public string fristA { get; set; }
        public string secondQ { get; set; }
        public string secondA { get; set; }
    
        public virtual ICollection<db_UserAddressInfo> db_UserAddressInfo { get; set; }
    }
}
