//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webshopDBEntities : DbContext
    {
        public webshopDBEntities()
            : base("name=webshopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<db_adinfo> db_adinfo { get; set; }
        public DbSet<db_AdminInfo> db_AdminInfo { get; set; }
        public DbSet<db_KindInfo> db_KindInfo { get; set; }
        public DbSet<db_MoneyType> db_MoneyType { get; set; }
        public DbSet<db_OrderInfo> db_OrderInfo { get; set; }
        public DbSet<db_orderStateInfo> db_orderStateInfo { get; set; }
        public DbSet<db_PostInfo> db_PostInfo { get; set; }
        public DbSet<db_ProductImgInfo> db_ProductImgInfo { get; set; }
        public DbSet<db_ProductInfo> db_ProductInfo { get; set; }
        public DbSet<db_sonkindInfo> db_sonkindInfo { get; set; }
        public DbSet<db_UserAddressInfo> db_UserAddressInfo { get; set; }
        public DbSet<db_UserInfo> db_UserInfo { get; set; }
    }
}
